### PR TITLE
Emergency to wait2

### PR DESCRIPTION
**Pull request by dkfellows**
_After_ #583 is merged (DO THAT ONE FIRST!), this cleans up the mess of naming of waiting so that we don't talk about emergency timeouts, but rather the much more relevant `wait1` and `wait2`.

### CODE REVIEW

**Comment by alan-stokes** [comment]
general issue that might just be nit picking. but most of the comments in the structs are beside the line, a few are above the line. classically we keep them above the line so that you dont get this mixtures of things............. should that be fixed? or is there some doxagen reasoning for this mix?

**Comment by dkfellows** [comment]
> general issue that might just be nit picking. but most of the comments in the structs are beside the line, a few are above the line. classically we keep them above the line so that you dont get this mixtures of things............. should that be fixed? or is there some doxagen reasoning for this mix?

Because of the way this PR has been done, it's a comment I'm not addressing here. It belongs on #583

**Comment by dkfellows** [comment]
(I think this PR is only about the changes to the Python files.)

**Comment by alan-stokes** [comment]
> > general issue that might just be nit picking. but most of the comments in the structs are beside the line, a few are above the line. classically we keep them above the line so that you dont get this mixtures of things............. should that be fixed? or is there some doxagen reasoning for this mix?
> 
> Because of the way this PR has been done, it's a comment I'm not addressing here. It belongs on #583

oops. yea. looks like i plonked it on the wrong pr. as you can see I've got both on my radar. lol

**Comment by dkfellows** [comment]
The first commit on this branch is c74ce25aa7eab01c51ee437b3c10e9cb5401daa9

**Comment by alan-stokes** [comment]
this looks fine. so when  #583 is done, this can be merged.

**Pull request merged**
