### PR TITLE
Deal with case where a vertex_slice has an array of empty arrays

### PR DESCRIPTION
**Pull request by andrewgait**
Fixes https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/issues/623

Tested by https://github.com/SpiNNakerManchester/sPyNNaker8/pull/416

### CODE REVIEW

**Comment by Christian-B** [comment]
I think this fixes it the wrong way around.

Now both the Application Vertex and the Machine vertex trigger the block 
which bases sdram on the receive_rate

This is incorrect as there in no live data.

It is incorrect to assume there will be on the one core whose splice has no values in the send_buffer_times.

So while the resources require now match they are now both wrong

**Comment by Christian-B** [comment]
I have added a log warning to track that there is a weirdness going on.

**Comment by andrewgait** [comment]
> I think this fixes it the wrong way around.
> 
> Now both the Application Vertex and the Machine vertex trigger the block
> which bases sdram on the receive_rate
> 
> This is incorrect as there in no live data.
> 
> It is incorrect to assume there will be live data on the one core whose splice has no values in the send_buffer_times.
> 
> So while the resources require now match they are now both wrong

I think you're right, but it's not necessarily straightforward to fix it the other way - it certainly involves more changes, maybe even to the buffer manager.  As you say maybe it's better to fix it this way but have a log warning.

**Comment by alan-stokes** [comment]
keeping branch for any reason?

**Pull request merged**
