### PR TITLE
better solution using non-standard app graphs

### PR DESCRIPTION
**Pull request by alan-stokes**
this makes these obsolete:

https://github.com/SpiNNakerManchester/PACMAN/pull/173
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/338

this allows the front end to get the max machine available directly (1 call) and therefore allows it to do its own partitioning, as long as the agreement that the machine graph meets the correct specs. 

this does open the hole for spynnaker version to be declaring its own partitioner. But looking at that separately. 

this will now allow the nengo spinnaker version to partition with at least a max machien context. Allowing sdram links, pre allocation res etc to be tied in.

### CODE REVIEW

**Comment by rowleya** [comment]
This seems to break something when using a real machine (this is va_benchmark.py):
```
Detected PyNN version 0.9.1 and Neo version 0.5.2
1200 300
['C:\\Users\\zzalsar4\\git\\SpiNNFrontEndCommon\\spinn_front_end_common\\interface\\spinnaker.cfg', 'C:\\Users\\zzalsar4\\git\\sPyNNaker\\spynnaker\\pyNN\\spynnaker.cfg', 'C:\\Users\\zzalsar4\\.spynnaker.cfg', 'C:\\Users\\zzalsar4\\spynnaker-spinn-9.cfg']
2018-07-27 17:30:59 INFO: Read cfg files: C:\Users\zzalsar4\git\SpiNNFrontEndCommon\spinn_front_end_common\interface\spinnaker.cfg, C:\Users\zzalsar4\git\sPyNNaker\spynnaker\pyNN\spynnaker.cfg, C:\Users\zzalsar4\.spynnaker.cfg, C:\Users\zzalsar4\spynnaker-spinn-9.cfg
2018-07-27 17:30:59 INFO: Will search these locations for binaries: C:\Users\zzalsar4\git\SpiNNFrontEndCommon\spinn_front_end_common\common_model_binaries : C:\Users\zzalsar4\git\sPyNNaker\spynnaker\pyNN\model_binaries
2018-07-27 17:30:59 WARNING: C:\Users\zzalsar4\git\PyNN8Examples\examples\application_generated_data_files has 29 old reports that have not been closed
2018-07-27 17:30:59 INFO: Setting time scale factor to 1.0.
2018-07-27 17:30:59 INFO: Setting machine time step to 1000.0 micro-seconds.
2018-07-27 17:30:59 WARNING: Extra params {'db_name': 'va_benchmark.sqlite', 'filename': 'va_CUBA.xml', 'threads': 1, 'label': 'VA'} have been applied to the setup command which we do not consider
Host #1 is on zzalsar4
0 Initialising the simulator with 1 thread(s)...
{'tau_refrac': 5.0, 'v_thresh': -50.0, 'tau_m': 20.0, 'tau_syn_E': 5.0, 'v_rest': -49.0, 'cm': 0.2, 'i_offset': 0, 'tau_syn_I': 10.0, 'v_reset': -60.0}
0 Creating cell populations...
0 Initialising membrane potential to random values...
0 Connecting populations...
0 Setting up recording...
0 Running simulation...
timings: number of neurons: 1500
timings: number of synapses: 45000.0
2018-07-27 17:30:59 INFO: Simulating for 1 1000.0ms timesteps using a hardware timestep of 1000000us
2018-07-27 17:30:59 INFO: Starting execution process
Traceback (most recent call last):
  File "C:\Users\zzalsar4\git\PyNN8Examples\examples\va_benchmark.py", line 203, in <module>
    p.run(tstop)
  File "C:\Users\zzalsar4\git\sPyNNaker8\spynnaker8\__init__.py", line 628, in run
    return __pynn["run"](simtime, callbacks=callbacks)
  File "C:\Users\zzalsar4\git\PyNN-0.9.1\PyNN9\pyNN\common\control.py", line 111, in run
    return run_until(simulator.state.t + simtime, callbacks)
  File "C:\Users\zzalsar4\git\PyNN-0.9.1\PyNN9\pyNN\common\control.py", line 93, in run_until
    simulator.state.run_until(time_point)
  File "C:\Users\zzalsar4\git\sPyNNaker8\spynnaker8\spinnaker.py", line 123, in run_until
    self._run_wait(tstop - self.t)
  File "C:\Users\zzalsar4\git\sPyNNaker8\spynnaker8\spinnaker.py", line 166, in _run_wait
    super(SpiNNaker, self).run(duration_ms)
  File "C:\Users\zzalsar4\git\sPyNNaker\spynnaker\pyNN\abstract_spinnaker_common.py", line 312, in run
    super(AbstractSpiNNakerCommon, self).run(run_time)
  File "C:\Users\zzalsar4\git\SpiNNFrontEndCommon\spinn_front_end_common\interface\abstract_spinnaker_base.py", line 843, in run
    self._run(run_time)
  File "C:\Users\zzalsar4\git\SpiNNFrontEndCommon\spinn_front_end_common\interface\abstract_spinnaker_base.py", line 961, in _run
    self._get_real_machine(total_run_time, n_machine_time_steps)
  File "C:\Users\zzalsar4\git\SpiNNFrontEndCommon\spinn_front_end_common\interface\abstract_spinnaker_base.py", line 1393, in _get_real_machine
    self._get_max_available_machine()
  File "C:\Users\zzalsar4\git\SpiNNFrontEndCommon\spinn_front_end_common\interface\abstract_spinnaker_base.py", line 1261, in _get_max_available_machine
    inputs, algorithms, outputs, [], [], "machine_generation")
  File "C:\Users\zzalsar4\git\SpiNNFrontEndCommon\spinn_front_end_common\interface\abstract_spinnaker_base.py", line 1208, in _run_algorithms
    provenance_path=self._pacman_executor_provenance_path)
  File "C:\Users\zzalsar4\git\PACMAN\pacman\executor\pacman_algorithm_executor.py", line 155, in __init__
    use_unscanned_annotated_algorithms, tokens, required_output_tokens)
  File "C:\Users\zzalsar4\git\PACMAN\pacman\executor\pacman_algorithm_executor.py", line 239, in _set_up_pacman_algorithm_listings
    tokens, required_output_tokens)
  File "C:\Users\zzalsar4\git\PACMAN\pacman\executor\pacman_algorithm_executor.py", line 450, in _determine_algorithm_order
    algorithm_input_requirement_breakdown))
pacman.exceptions.PacmanConfigurationException: Unable to deduce a future algorithm to use.
    Inputs: set(['BootPortNum', 'DownedLinksDetails', 'BoardVersion', 'DownedChipsDetails', 'DownedCoresDetails', 'ScampConnectionData', 'ResetMachineOnStartupFlag', 'BMPDetails', 'IPAddress', 'AutoDetectBMPFlag', 'MaxCoreId'])
    Fake Inputs: set(['MAxCoreID'])
    Outputs to find: set(['MemoryTransceiver', 'MemoryMachine'])
    Tokens complete: []
    Fake tokens complete: []
    Tokens to find: set([])
    Required algorithms remaining to be used: ['MachineGenerator']
    Optional Algorithms unused: []
    Functions used: []
    Algorithm by outputs: defaultdict(<type 'list'>, {'MemoryTransceiver': ['MachineGenerator'], 'MemoryMachine': ['MachineGenerator']})
    Algorithm by tokens: defaultdict(<type 'list'>, {})
    Inputs required per function: 
            MachineGenerator: ['['MaxSDRAMSize']']
```

**Comment by alan-stokes** [comment]
mmmmmm....... looks like the sdram thing is put in a moment too late. fixed in last commit. I think.

**Comment by rowleya** [comment]
I have done some merges on this, but it still doesn't work, and seems fundamentally flawed.  The issue is that get_number_of_cores_available_on_machine now tries to get the real machine, which then seems to have an issue because there is no machine_graph or application_graph at this point.  Given that the graph is built after this call, this is no surprise.

This needs some work before merging...

**Comment by alan-stokes** [comment]
ill relook at it at some point. given its a nengo related thing. when is up in the air

**Comment by dkfellows** [comment]
Postpone to post-5?

**Pull request closed without merging**
