### PR TITLE
Json graphs

### PR DESCRIPTION
**Pull request by Christian-B**
changes needed to write json graphs. https://github.com/SpiNNakerManchester/PACMAN/pull/287

Set the following [Reports] values in the cfg for this to generate the json to do offline routing tests.

write_json_graphs = True

And optionally the other write json ones

### CODE REVIEW

**Comment by pabogdan** [comment]
@Christian-B, @rowleya  is this branch compatible with pop_based_master_pop_table?

**Comment by rowleya** [comment]
Yes, it should be; this just adds JSON files.

**Comment by Christian-B** [comment]
Lets wait for View and reduce overhead and then see what we need

**Comment by Christian-B** [comment]
pr this enables closed as too far out of date

**Pull request closed without merging**
