### PR TITLE
fixes for config and getboolean

### PR DESCRIPTION
**Pull request by alan-stokes**
fixes issues with config.get and config.getboolean

p.s. we should build some simple tests to ensure this wont hit us again.

### CODE REVIEW

**Comment by rowleya** [comment]
Should really have a test, but I can see how hard such a test would be and that it wouldn't actually be of much use...

**Comment by alan-stokes** [comment]
thats why i plonked it as a comment. i imagine christian will take the challenge and figure a way of detecting it all. It is what he does afterall. lol

**Comment by rowleya** [comment]
Though I am happy with a test, I can't see a test helping us to not make this mistake again in the future elsewhere in the code.  The only test would be that provenance data gathering is done when the option is turned on I guess...

**Comment by rowleya** [comment]
Or else that it is not done when turned off

**Comment by alan-stokes** [comment]
talking of that line of stuff, theres a issue with reports for multiple calls to run. it seems (from peters version) that p.run(x) p.run(y) does not produce two run folders. it plonks them into the same folder in run1, and uses the unqiue identifier to get around the issue that the file already exists. im opening up a issue for it so that we can chase this down in the future

**Pull request merged**
