### PR TITLE
only write database on first run and remapping

### PR DESCRIPTION
**Pull request by alan-stokes**
i think this works, but cant test. laptop gone weird and turned into read only on the partition with software

### CODE REVIEW

**Comment by alan-stokes** [comment]
hopefully fixes https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/issues/283

**Comment by rowleya** [comment]
This makes loads of changes that seem irrelevant to this change and it fails loads of tests.  Is there something specific this is supposed to be changing?

**Comment by alan-stokes** [comment]
unknown why thers that many line changed. it should have only 4 or 5 lines changed. ...... maybe due to being so far out from master?

**Comment by rowleya** [comment]
The state you see here is at the point when it was created.  It looks like this was started from an unclean point...  It may be worth redoing this if the change is easy enough.  I can't work out which part was meant to be changed or I would do it myself!

**Comment by alan-stokes** [comment]
added to my pile for after data in fixed.

**Comment by andrewgait** [comment]
> The state you see here is at the point when it was created. It looks like this was started from an unclean point... It may be worth redoing this if the change is easy enough. I can't work out which part was meant to be changed or I would do it myself!

I agree with this - this probably needs redoing from a more up-to-date point in master.

**Comment by dkfellows** [comment]
Data In should now be fixed enough that this can be reconsidered.

**Comment by rowleya** [comment]
That's a bit simpler!

**Comment by rowleya** [comment]
I believe that this now works having tested it (it writes the database at the start if needed and then only if the graph changes)

**Comment by alan-stokes** [comment]
thanks for picking this up.

**Pull request merged**
