### PR TITLE
Better handling of binaries

### PR DESCRIPTION
**Pull request by rowleya**
Fix to not need executables when in virtual mode

### CODE REVIEW

**Comment by rowleya** [comment]
Tested by SpiNNakerManchester/sPyNNaker8#369 (mainly the unit tests in this case)

**Comment by Christian-B** [comment]
I would like to see this tested with a cherry pick from https://github.com/SpiNNakerManchester/SpiNNUtils/pull/88

**Comment by rowleya** [comment]
I did think about doing that; the cherry pick was complex because the commits weren't isolated.  I will have a look and see if I can extract the important bit

**Comment by rowleya** [comment]
OK, I have created this PR in SpiNNUtils: SpiNNakerManchester/SpiNNUtils#113.  Will now force-rerun tests...

**Comment by rowleya** [comment]
From what I can see in the unit tests of sPyNNaker8, it works correctly even when the ExecutableFinder raises an Exception when binaries are not found.

**Pull request merged**
