### PR TITLE
Parallel java

### PR DESCRIPTION
**Pull request by alan-stokes**
for project completeness

needs 
- [ ] https://github.com/SpiNNakerManchester/SpiNNMan/pull/119#issuecomment-383072942

### CODE REVIEW

**Comment by dkfellows** [comment]
Baseline branch is broken.

**Comment by Christian-B** [comment]
doesnt pass travish. so not reviewing just now

**Comment by dkfellows** [comment]
No longer relevant; obsoleted by #372

**Comment by alan-stokes** [comment]
can we delete the branch then?

**Pull request closed without merging**
