### PR TITLE
Removal of re injector from spinnMan and into FEC

### PR DESCRIPTION
**Pull request by alan-stokes**
this allows us to then insert the data gathering components into extra monitors cores.

depends upon:
- [x] https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/214
- [x] https://github.com/SpiNNakerManchester/sPyNNaker/pull/427
- [x] https://github.com/SpiNNakerManchester/SpiNNakerGraphFrontEnd/pull/70
- [x] merge https://github.com/SpiNNakerManchester/SpiNNMan/pull/97 
- [x] merge https://github.com/SpiNNakerManchester/SupportScripts/pull/4
- [x] merge https://github.com/SpiNNakerManchester/PACMAN/pull/125

### CODE REVIEW

**Comment by Christian-B** [comment]
.travis.xml needs updating to build the stuff no longer done in spinnman.

Maybe @dkfellows can help here

**Comment by dkfellows** [comment]
The build is still broken, but now it is broken in ways that don't involve the build script.

**Comment by alan-stokes** [comment]
will look at shortly

**Comment by dkfellows** [comment]
Changeset fully approved. Any problems are now Alan's bugs. 😆

**Pull request merged**
