### PR TITLE
Revert "Revert "Fix router table copy""

### PR DESCRIPTION
**Pull request by rowleya**
Reinstate this;  it is currently broken so needs fixing first...

### CODE REVIEW

**Comment by Christian-B** [comment]
Before merging please test with a spin three board.

For example with fast on run in one go the three tests in 
https://github.com/SpiNNakerManchester/sPyNNaker8/tree/master/p8_integration_tests/quick_test/test_debug_mode

**Comment by alan-stokes** [comment]
??????????? do we need this? is there still a bug?

**Comment by alan-stokes** [comment]
if there is a bug. dont we want to ensure we solve it before the release?

**Comment by rowleya** [comment]
If the existing code is working without issues, it may be worth not bothering with this.

**Comment by alan-stokes** [comment]
given that vague memories says this made bugs, not solved bugs...... i'm inclined to burn it to the ground.

**Comment by rowleya** [comment]
Yes, this version did introduce some bugs.  I don't know if it is worth keeping the work just in case, but the PR can be closed.

**Comment by rowleya** [comment]
Keeping in case it becomes useful

**Comment by alan-stokes** [comment]
question. maybe we can have a project for these kinda things. blue sky prs that we keep around, and then it would be easier in future to see if we ever really do want them again?

**Comment by rowleya** [comment]
Sounds like a good idea

**Comment by alan-stokes** [comment]
cant be. i made it. but fine. will set it up. any other prs you want in there off the top of your head?

**Comment by rowleya** [comment]
Nothing I can think of.  Question; do we want to leave the PRs open?  I guess we can filter out the project...

**Comment by alan-stokes** [comment]
i cant put them in the project if they closed i think.

**Comment by alan-stokes** [comment]
meh. still in project. fine. left now

**Pull request closed without merging**
