### PR TITLE
Avoid mode debug setting zero to True

### PR DESCRIPTION
**Pull request by Christian-B**

### CODE REVIEW

**Comment by alan-stokes** [comment]
this would be a problem for all get_booleans. I dont the reasoning for treating this one differently.

**Comment by Christian-B** [comment]
Went for more of a harc code in Options approach as discussed.

**Comment by rowleya** [comment]
Seems to have a Flake8 Error.  This is marked as for merging before release.  Is this still desired?

**Comment by Christian-B** [comment]
Yes this needs merging ASAP or Mode debug will always fail!

**Pull request merged**
