### PR TITLE
N boards

### PR DESCRIPTION
**Pull request by Christian-B**
Partial work for https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/issues/416

Adds n_boards but still has n_chips until the way the machine needed is changed.

Must be done at the same time as:
https://github.com/SpiNNakerManchester/sPyNNaker/pull/697
https://github.com/SpiNNakerManchester/sPyNNaker8/pull/255
https://github.com/SpiNNakerManchester/SpiNNakerGraphFrontEnd/pull/122

### CODE REVIEW

**Comment by andrewgait** [comment]
Looks good to me.  This ready to merge now?

**Comment by andrewgait** [comment]
Merging.  Note: tested this using MarkovChainMonteCarlo and it's a much better way of specifying a number of boards than trying to estimate it using n_chips_required.

**Comment by alan-stokes** [comment]
just a stupid question. but when your pushing n boards up to the the top level. have you planned for all the system core requirements? aka extra monitors/reinejctors etc

**Comment by Christian-B** [comment]
This PR ONLY handles the case where the user specifically requests a number of boards in the setup call.

I will not work on the automated calculation which MUST of course include the extra monitors/reinejctors etc
see
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/issues/416

**Pull request merged**
