### PR TITLE
Allows vm reporting of cores and links

### PR DESCRIPTION
**Pull request by alan-stokes**
alas depends on max machine, coz i didnt relise where i was. but this allows the vm to report its cores and links. which is the expected behaviour of our tools when buidling a machine. But only happens when a spinnMan is invovled currently.

### CODE REVIEW

**Comment by Christian-B** [comment]
This branch has conflicts if I merge in master on VirtualMachineGenerator

**Comment by alan-stokes** [comment]
i boiled this down to what the pr was on about. the stuff in ASB i think was trying to separate max machine from machine. but given i cant remember why, and that it was so far behind and had such a massive conflict in the key area. i just killed it. if the bug ever returns we can fix it then and there. 

so this is now a trival change and should be accepted with no problem now

**Comment by rowleya** [comment]
This is still behind master... maybe why Travis isn't working on it?

**Comment by alan-stokes** [comment]
bought back up with master. is travis now working?

**Pull request merged**
