### PR TITLE
preallocating Extra monitor fix

### PR DESCRIPTION
**Pull request by Christian-B**
fix for https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/issues/328

### CODE REVIEW

**Comment by Christian-B** [comment]
tested with a monster neuron and this causes the partitioner to split the neuron slightly different  so it looks ok.

**Comment by alan-stokes** [comment]
bouched given feedback

**Comment by Christian-B** [comment]
Depends on https://github.com/SpiNNakerManchester/PACMAN/pull/163 to work correctly in all cases

**Comment by Christian-B** [comment]
@alan-stokes Please explain "bouched given feedback"

If this before or after todays changes?

**Comment by alan-stokes** [comment]
before todays changes. i now approve. rubbering shortly, just need to find the stamp

**Pull request merged**
